---
- hosts: "{{ hostname }}"
  gather_facts: no
  tasks:
    - name: create directory
      file:
        path: "{{ dir_path }}"
        state: directory
        mode: "{{ dir_mode }}"
        owner: "{{ dir_owner }}"
        group: "{{ dir_group_owner }}"
        serole: "{{ dir_serole | default(omit) }}"
        setype: "{{ dir_setype | default(omit) }}"
        seuser: "{{ dir_seuser | default(omit) }}"
        selevel: "{{ dir_selevel | default(omit) }}"
